name: CI

on: [push, pull_request]

jobs:
  theme-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Theme Check
        run: gem install theme-check

      - name: Run Theme Check
        run: theme-check
